server:
  port: 8080
spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: msvc-user
          uri: lb://msvc-user
          predicates:
            - Path=/user/**
        - id: msvc-car
          uri: lb://msvc-car
          predicates:
            - Path=/car/**
        - id: msvc-bike
          uri: lb://msvc-bike
          predicates:
            - Path=/bike/**

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
