spring:
  application:
    name: msvc-user
  cloud:
    config:
      enabled: true
      uri: http://localhost:8080
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect